version: '3'
services:
  redis:
    image: "redis:3.2.11"
    container_name: "holder-redis3.2"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      mynet:
        ipv4_address: 172.26.238.105

networks:
  mynet:
    external:
      name: holder-network
