version: '3'
services:
  nginx:
    image: "nginx:1.13.7"
    container_name: "holder-nginx"
    ports:
      - "80:80"
      - "90:90"
      - "91:91"
      - "100:100"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./crm:/usr/share/nginx/crm
      - ./jyds:/usr/share/nginx/jyds
      - ./pay:/usr/share/nginx/pay
      - ./nginx.conf:/etc/nginx/conf.d
      - ./log:/var/log/nginx
    networks:
      mynet:
        ipv4_address: 172.26.238.100

networks:
  mynet:
    external:
      name: holder-network
